# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    F1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    F2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    F3_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    F4_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    F5_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

F1_controller:
  ros__parameters:
    joints:
      - j_1_1
      - j_1_2
      - j_1_3
      - j_1_4
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
F2_controller:
  ros__parameters:
    joints:
      - j_2_1
      - j_2_2
      - j_2_3
      - j_2_4
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
F3_controller:
  ros__parameters:
    joints:
      - j_3_1
      - j_3_2
      - j_3_3
      - j_3_4
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
F4_controller:
  ros__parameters:
    joints:
      - j_4_1
      - j_4_2
      - j_4_3
      - j_4_4
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
F5_controller:
  ros__parameters:
    joints:
      - j_5_1
      - j_5_2
      - j_5_3
      - j_5_4
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position